apiVersion: v1
kind: Service
metadata:
  name: sample-backend-service
  namespace: forgecloud-apps
  labels:
    app.kubernetes.io/name: sample-backend-service
    app.kubernetes.io/part-of: forgecloud-apps
    app.kubernetes.io/component: sample-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sample-backend-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
