apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: forgecloud-system
  labels:
    app.kubernetes.io/name: backend-sa
    app.kubernetes.io/part-of: forgecloud
    app.kubernetes.io/component: control-plane
automountServiceAccountToken: false
