apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: forgecloud-system
  labels:
    app.kubernetes.io/name: frontend-sa
    app.kubernetes.io/part-of: forgecloud
    app.kubernetes.io/component: presentation
automountServiceAccountToken: false
