apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app-sa
  namespace: forgecloud-apps
  labels:
    app.kubernetes.io/name: sample-app-sa
    app.kubernetes.io/part-of: forgecloud-apps
    app.kubernetes.io/component: sample-app
automountServiceAccountToken: false
